In [5]:
import sqlite3
import pandas as pd
import json

In [6]:
#These Json Files contain the CNG Groupings 
dictnoun = json.load(open("noungroups.json"))
dictverb = json.load(open("verbgroups.json"))

In [16]:
conn = sqlite3.connect("Extracted.db")

In [8]:
df = pd.DataFrame(columns = ["CNG", "CNG_Group"])
#defining a dataframe in which we have the list of all CNG_Groups to which a CNG Belongs
#We define it in such a way because we want to use it in an inner join to add CNG_Group nodes in the graph.

In [9]:
df

Empty DataFrame
Columns: [CNG, CNG_Group]
Index: []

In [11]:
z =0
#z = index of the dataframe

for key in dictnoun.keys():
    #key is a CNG_Group
    for value in dictnoun[key]:
        #value is CNG
        df.loc[z] = [value, key]
        #storing CNG and its GROUP
        z += 1
        #incrementing index

In [12]:
df.head()

   CNG    CNG_Group
0   92  instr. adj.
1   97  instr. adj.
2  102  instr. adj.
3   30          fem
4   35          fem

In [14]:
#same as above but for verbs groups
for key in dictverb.keys():
    for value in dictverb[key]:
        df.loc[z] = [(-1)*value, key]
        #-1 is multipled as CNG of Verbs are negative.
        z += 1

In [15]:
df

       CNG    CNG_Group
0       92  instr. adj.
1       97  instr. adj.
2      102  instr. adj.
3       30          fem
4       35          fem
5       40          fem
6       50          fem
7       55          fem
8       60          fem
9       70          fem
10      75          fem
11      80          fem
12      90          fem
13      95          fem
14     100          fem
15     110          fem
16     115          fem
17     120          fem
18     130          fem
19     135          fem
20     140          fem
21     150          fem
22     155          fem
23     160          fem
24     170          fem
25     175          fem
26     180          fem
27      79     acc. pl.
28      80     acc. pl.
29      81     acc. pl.
...    ...          ...
1119  -114        11_fp
1120  -111        11_fp
1121  -301        30_sg
1122  -302        30_sg
1123  -303        30_sg
1124   -21         2_sg
1125   -22         2_sg
1126   -23         2_sg
1127   -25         2_sp
1128   -28         2_sp
1129   -22         2_sp
1130  -179        17_pl
1131  -251        25_sg
1132  -252        25_sg
1133  -253        25_sg
1134  -154        15_fp
1135  -157        15_fp
1136  -151        15_fp
1137  -142        14_sp
1138  -272        27_sp
1139  -278        27_sp
1140   -37         3_pl
1141   -38         3_pl
1142   -39         3_pl
1143   -66         6_tp
1144   -69         6_tp
1145   -63         6_tp
1146   -32         3_sg
1147   -33         3_sg
1148   -31         3_sg

[1149 rows x 2 columns]

In [17]:
df.to_sql("CNG&CNGG", conn)
#dumping data in a table

In [18]:
conn.close()